globals
    // Generated
trigger gg_trg_Melee_Initialization= null

    // Random Groups
integer array gg_rg_000
integer array gg_rg_001
integer array gg_rg_002


//JASSHelper struct globals:

endglobals


//===========================================================================
// 
// Sample #3
// 
//   Warcraft III map script
//   Generated by the Warcraft III World Editor
//   Date: Wed Aug 14 21:23:51 2019
//   Map Author: Marcelo Hossomi
// 
//===========================================================================

//***************************************************************************
//*
//*  Global Variables
//*
//***************************************************************************


function InitGlobals takes nothing returns nothing
endfunction

//***************************************************************************
//*
//*  Custom Script Code
//*
//***************************************************************************

//***************************************************************************
//*
//*  Random Groups
//*
//***************************************************************************

function InitRandomGroups takes nothing returns nothing
    local integer curset

    // Group 0 - Group 1
    call RandomDistReset()
    call RandomDistAddItem(0, 34)
    call RandomDistAddItem(1, 33)
    call RandomDistAddItem(2, 33)
    set curset=RandomDistChoose()

    if ( curset == 0 ) then
        set gg_rg_000[0]='nanb'
        set gg_rg_000[1]='ngme'
        set gg_rg_000[2]='ratf'
    elseif ( curset == 1 ) then
        set gg_rg_000[0]=ChooseRandomCreep(- 1)
        set gg_rg_000[1]=ChooseRandomNPBuilding()
        set gg_rg_000[2]=ChooseRandomItemEx(ITEM_TYPE_ANY, - 1)
    elseif ( curset == 2 ) then
        set gg_rg_000[0]=ChooseRandomCreep(10)
        set gg_rg_000[1]=- 1
        set gg_rg_000[2]=ChooseRandomItemEx(ITEM_TYPE_ARTIFACT, 5)
    else
        set gg_rg_000[0]=- 1
        set gg_rg_000[1]=- 1
        set gg_rg_000[2]=- 1
    endif

    // Group 1 - Group 2
    call RandomDistReset()
    call RandomDistAddItem(0, 75)
    call RandomDistAddItem(- 1, 25)
    set curset=RandomDistChoose()

    if ( curset == 0 ) then
        set gg_rg_001[0]='nplb'
    else
        set gg_rg_001[0]=- 1
    endif

    // Group 2 - Group 3
    call RandomDistReset()
    call RandomDistAddItem(0, 100)
    set curset=RandomDistChoose()

    if ( curset == 0 ) then
        set gg_rg_002[0]='nbda'
        set gg_rg_002[1]='ckng'
    else
        set gg_rg_002[0]=- 1
        set gg_rg_002[1]=- 1
    endif

endfunction

//***************************************************************************
//*
//*  Map Item Tables
//*
//***************************************************************************

function ItemTable000000_DropItems takes nothing returns nothing
    local widget trigWidget= null
    local unit trigUnit= null
    local integer itemID= 0
    local boolean canDrop= true

    set trigWidget=bj_lastDyingWidget
    if ( trigWidget == null ) then
        set trigUnit=GetTriggerUnit()
    endif

    if ( trigUnit != null ) then
        set canDrop=not IsUnitHidden(trigUnit)
        if ( canDrop and GetChangingUnit() != null ) then
            set canDrop=( GetChangingUnitPrevOwner() == Player(PLAYER_NEUTRAL_AGGRESSIVE) )
        endif
    endif

    if ( canDrop ) then
        // Item set 0
        call RandomDistReset()
        call RandomDistAddItem('ratf', 50)
        call RandomDistAddItem('ckng', 50)
        set itemID=RandomDistChoose()
        if ( trigUnit != null ) then
            call UnitDropItem(trigUnit, itemID)
        else
            call WidgetDropItem(trigWidget, itemID)
        endif

        // Item set 1
        call RandomDistReset()
        call RandomDistAddItem(ChooseRandomItemEx(ITEM_TYPE_POWERUP, 4), 50)
        call RandomDistAddItem(- 1, 50)
        set itemID=RandomDistChoose()
        if ( trigUnit != null ) then
            call UnitDropItem(trigUnit, itemID)
        else
            call WidgetDropItem(trigWidget, itemID)
        endif

        // Item set 2
        call RandomDistReset()
        call RandomDistAddItem(gg_rg_000[2], 40)
        call RandomDistAddItem(gg_rg_002[1], 60)
        set itemID=RandomDistChoose()
        if ( trigUnit != null ) then
            call UnitDropItem(trigUnit, itemID)
        else
            call WidgetDropItem(trigWidget, itemID)
        endif

    endif

    set bj_lastDyingWidget=null
    call DestroyTrigger(GetTriggeringTrigger())
endfunction

function ItemTable000001_DropItems takes nothing returns nothing
    local widget trigWidget= null
    local unit trigUnit= null
    local integer itemID= 0
    local boolean canDrop= true

    set trigWidget=bj_lastDyingWidget
    if ( trigWidget == null ) then
        set trigUnit=GetTriggerUnit()
    endif

    if ( trigUnit != null ) then
        set canDrop=not IsUnitHidden(trigUnit)
        if ( canDrop and GetChangingUnit() != null ) then
            set canDrop=( GetChangingUnitPrevOwner() == Player(PLAYER_NEUTRAL_AGGRESSIVE) )
        endif
    endif

    if ( canDrop ) then
        // Item set 0
        call RandomDistReset()
        call RandomDistAddItem(ChooseRandomItemEx(ITEM_TYPE_ANY, - 1), 1)
        call RandomDistAddItem(ChooseRandomItemEx(ITEM_TYPE_PERMANENT, - 1), 2)
        call RandomDistAddItem(ChooseRandomItemEx(ITEM_TYPE_CHARGED, - 1), 3)
        call RandomDistAddItem(ChooseRandomItemEx(ITEM_TYPE_POWERUP, - 1), 4)
        call RandomDistAddItem(ChooseRandomItemEx(ITEM_TYPE_ARTIFACT, - 1), 5)
        call RandomDistAddItem(ChooseRandomItemEx(ITEM_TYPE_PURCHASABLE, - 1), 6)
        call RandomDistAddItem(ChooseRandomItemEx(ITEM_TYPE_CAMPAIGN, - 1), 7)
        call RandomDistAddItem(ChooseRandomItemEx(ITEM_TYPE_MISCELLANEOUS, - 1), 8)
        call RandomDistAddItem(- 1, 64)
        set itemID=RandomDistChoose()
        if ( trigUnit != null ) then
            call UnitDropItem(trigUnit, itemID)
        else
            call WidgetDropItem(trigWidget, itemID)
        endif

    endif

    set bj_lastDyingWidget=null
    call DestroyTrigger(GetTriggeringTrigger())
endfunction


//***************************************************************************
//*
//*  Triggers
//*
//***************************************************************************

//===========================================================================
// Trigger: Melee Initialization
//
// Default melee game initialization for all players
//===========================================================================
function Trig_Melee_Initialization_Actions takes nothing returns nothing
    call MeleeStartingVisibility()
    call MeleeStartingHeroLimit()
    call MeleeGrantHeroItems()
    call MeleeStartingResources()
    call MeleeClearExcessUnits()
    call MeleeStartingUnits()
    call MeleeStartingAI()
    call MeleeInitVictoryDefeat()
endfunction

//===========================================================================
function InitTrig_Melee_Initialization takes nothing returns nothing
    set gg_trg_Melee_Initialization=CreateTrigger()
    call TriggerAddAction(gg_trg_Melee_Initialization, function Trig_Melee_Initialization_Actions)
endfunction

//===========================================================================
function InitCustomTriggers takes nothing returns nothing
    call InitTrig_Melee_Initialization()
endfunction

//===========================================================================
function RunInitializationTriggers takes nothing returns nothing
    call ConditionalTriggerExecute(gg_trg_Melee_Initialization)
endfunction

//***************************************************************************
//*
//*  Players
//*
//***************************************************************************

function InitCustomPlayerSlots takes nothing returns nothing

    // Player 0
    call SetPlayerStartLocation(Player(0), 0)
    call SetPlayerColor(Player(0), ConvertPlayerColor(0))
    call SetPlayerRacePreference(Player(0), RACE_PREF_HUMAN)
    call SetPlayerRaceSelectable(Player(0), true)
    call SetPlayerController(Player(0), MAP_CONTROL_USER)

endfunction

function InitCustomTeams takes nothing returns nothing
    // Force: TRIGSTR_006
    call SetPlayerTeam(Player(0), 0)

endfunction

//***************************************************************************
//*
//*  Main Initialization
//*
//***************************************************************************

//===========================================================================
function main takes nothing returns nothing
    call SetCameraBounds(- 3328.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), - 3584.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM), 3328.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), 3072.0 - GetCameraMargin(CAMERA_MARGIN_TOP), - 3328.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), 3072.0 - GetCameraMargin(CAMERA_MARGIN_TOP), 3328.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), - 3584.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM))
    call SetDayNightModels("Environment\\DNC\\DNCLordaeron\\DNCLordaeronTerrain\\DNCLordaeronTerrain.mdl", "Environment\\DNC\\DNCLordaeron\\DNCLordaeronUnit\\DNCLordaeronUnit.mdl")
    call NewSoundEnvironment("Default")
    call SetAmbientDaySound("IceCrownDay")
    call SetAmbientNightSound("IceCrownNight")
    call SetMapMusic("Music", true, 0)
    call InitRandomGroups()
    call InitBlizzard()


    call InitGlobals()
    call InitTrig_Melee_Initialization() // INLINED!!
    call ConditionalTriggerExecute(gg_trg_Melee_Initialization) // INLINED!!

endfunction

//***************************************************************************
//*
//*  Map Configuration
//*
//***************************************************************************

function config takes nothing returns nothing
    call SetMapName("TRIGSTR_001")
    call SetMapDescription("TRIGSTR_003")
    call SetPlayers(1)
    call SetTeams(1)
    call SetGamePlacement(MAP_PLACEMENT_USE_MAP_SETTINGS)

    call DefineStartLocation(0, 0.0, 0.0)

    // Player setup
    call InitCustomPlayerSlots()
    call SetPlayerSlotAvailable(Player(0), MAP_CONTROL_USER)
    call InitGenericPlayerSlots()
endfunction




//Struct method generated initializers/callers:

