globals
    // Generated
trigger gg_trg_Melee_Initialization= null


//JASSHelper struct globals:

endglobals


//===========================================================================
// 
// Sample #1
// 
//   Warcraft III map script
//   Generated by the Warcraft III World Editor
//   Date: Wed Aug 14 15:45:39 2019
//   Map Author: Marcelo Hossomi
// 
//===========================================================================

//***************************************************************************
//*
//*  Global Variables
//*
//***************************************************************************


function InitGlobals takes nothing returns nothing
endfunction

//***************************************************************************
//*
//*  Custom Script Code
//*
//***************************************************************************

//***************************************************************************
//*
//*  Unit Creation
//*
//***************************************************************************

//===========================================================================
function CreateUnitsForPlayer0 takes nothing returns nothing
    local player p= Player(0)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u=CreateUnit(p, 'Hblm', 2.6, - 6.2, 45.000)
endfunction

//===========================================================================
function CreatePlayerBuildings takes nothing returns nothing
endfunction

//===========================================================================
function CreatePlayerUnits takes nothing returns nothing
    call CreateUnitsForPlayer0()
endfunction

//===========================================================================
function CreateAllUnits takes nothing returns nothing
    call CreatePlayerBuildings()
    call CreateUnitsForPlayer0() // INLINED!!
endfunction

//***************************************************************************
//*
//*  Triggers
//*
//***************************************************************************

//===========================================================================
// Trigger: Melee Initialization
//
// Default melee game initialization for all players
//===========================================================================
function Trig_Melee_Initialization_Actions takes nothing returns nothing
    call MeleeStartingVisibility()
    call MeleeStartingHeroLimit()
    call MeleeGrantHeroItems()
    call MeleeStartingResources()
    call MeleeClearExcessUnits()
    call MeleeStartingUnits()
    call MeleeStartingAI()
    call MeleeInitVictoryDefeat()
endfunction

//===========================================================================
function InitTrig_Melee_Initialization takes nothing returns nothing
    set gg_trg_Melee_Initialization=CreateTrigger()
    call TriggerAddAction(gg_trg_Melee_Initialization, function Trig_Melee_Initialization_Actions)
endfunction

//===========================================================================
function InitCustomTriggers takes nothing returns nothing
    call InitTrig_Melee_Initialization()
endfunction

//===========================================================================
function RunInitializationTriggers takes nothing returns nothing
    call ConditionalTriggerExecute(gg_trg_Melee_Initialization)
endfunction

//***************************************************************************
//*
//*  Players
//*
//***************************************************************************

function InitCustomPlayerSlots takes nothing returns nothing

    // Player 0
    call SetPlayerStartLocation(Player(0), 0)
    call SetPlayerColor(Player(0), ConvertPlayerColor(0))
    call SetPlayerRacePreference(Player(0), RACE_PREF_HUMAN)
    call SetPlayerRaceSelectable(Player(0), false)
    call SetPlayerController(Player(0), MAP_CONTROL_USER)

    // Player 1
    call SetPlayerStartLocation(Player(1), 1)
    call SetPlayerColor(Player(1), ConvertPlayerColor(1))
    call SetPlayerRacePreference(Player(1), RACE_PREF_HUMAN)
    call SetPlayerRaceSelectable(Player(1), false)
    call SetPlayerController(Player(1), MAP_CONTROL_USER)

    // Player 2
    call SetPlayerStartLocation(Player(2), 2)
    call SetPlayerColor(Player(2), ConvertPlayerColor(2))
    call SetPlayerRacePreference(Player(2), RACE_PREF_HUMAN)
    call SetPlayerRaceSelectable(Player(2), false)
    call SetPlayerController(Player(2), MAP_CONTROL_USER)

    // Player 6
    call SetPlayerStartLocation(Player(6), 3)
    call SetPlayerColor(Player(6), ConvertPlayerColor(6))
    call SetPlayerRacePreference(Player(6), RACE_PREF_ORC)
    call SetPlayerRaceSelectable(Player(6), false)
    call SetPlayerController(Player(6), MAP_CONTROL_COMPUTER)

    // Player 7
    call SetPlayerStartLocation(Player(7), 4)
    call SetPlayerColor(Player(7), ConvertPlayerColor(7))
    call SetPlayerRacePreference(Player(7), RACE_PREF_ORC)
    call SetPlayerRaceSelectable(Player(7), false)
    call SetPlayerController(Player(7), MAP_CONTROL_COMPUTER)

    // Player 8
    call SetPlayerStartLocation(Player(8), 5)
    call SetPlayerColor(Player(8), ConvertPlayerColor(8))
    call SetPlayerRacePreference(Player(8), RACE_PREF_ORC)
    call SetPlayerRaceSelectable(Player(8), false)
    call SetPlayerController(Player(8), MAP_CONTROL_COMPUTER)

    // Player 12
    call SetPlayerStartLocation(Player(12), 6)
    call ForcePlayerStartLocation(Player(12), 6)
    call SetPlayerColor(Player(12), ConvertPlayerColor(12))
    call SetPlayerRacePreference(Player(12), RACE_PREF_UNDEAD)
    call SetPlayerRaceSelectable(Player(12), false)
    call SetPlayerController(Player(12), MAP_CONTROL_NEUTRAL)

    // Player 13
    call SetPlayerStartLocation(Player(13), 7)
    call ForcePlayerStartLocation(Player(13), 7)
    call SetPlayerColor(Player(13), ConvertPlayerColor(13))
    call SetPlayerRacePreference(Player(13), RACE_PREF_UNDEAD)
    call SetPlayerRaceSelectable(Player(13), false)
    call SetPlayerController(Player(13), MAP_CONTROL_NEUTRAL)

    // Player 14
    call SetPlayerStartLocation(Player(14), 8)
    call ForcePlayerStartLocation(Player(14), 8)
    call SetPlayerColor(Player(14), ConvertPlayerColor(14))
    call SetPlayerRacePreference(Player(14), RACE_PREF_UNDEAD)
    call SetPlayerRaceSelectable(Player(14), false)
    call SetPlayerController(Player(14), MAP_CONTROL_NEUTRAL)

    // Player 21
    call SetPlayerStartLocation(Player(21), 9)
    call ForcePlayerStartLocation(Player(21), 9)
    call SetPlayerColor(Player(21), ConvertPlayerColor(21))
    call SetPlayerRacePreference(Player(21), RACE_PREF_NIGHTELF)
    call SetPlayerRaceSelectable(Player(21), false)
    call SetPlayerController(Player(21), MAP_CONTROL_RESCUABLE)
    call SetPlayerAlliance(Player(21), Player(0), ALLIANCE_RESCUABLE, true)
    call SetPlayerAlliance(Player(21), Player(1), ALLIANCE_RESCUABLE, true)
    call SetPlayerAlliance(Player(21), Player(2), ALLIANCE_RESCUABLE, true)

    // Player 22
    call SetPlayerStartLocation(Player(22), 10)
    call ForcePlayerStartLocation(Player(22), 10)
    call SetPlayerColor(Player(22), ConvertPlayerColor(22))
    call SetPlayerRacePreference(Player(22), RACE_PREF_NIGHTELF)
    call SetPlayerRaceSelectable(Player(22), false)
    call SetPlayerController(Player(22), MAP_CONTROL_RESCUABLE)
    call SetPlayerAlliance(Player(22), Player(0), ALLIANCE_RESCUABLE, true)
    call SetPlayerAlliance(Player(22), Player(1), ALLIANCE_RESCUABLE, true)
    call SetPlayerAlliance(Player(22), Player(2), ALLIANCE_RESCUABLE, true)

    // Player 23
    call SetPlayerStartLocation(Player(23), 11)
    call ForcePlayerStartLocation(Player(23), 11)
    call SetPlayerColor(Player(23), ConvertPlayerColor(23))
    call SetPlayerRacePreference(Player(23), RACE_PREF_NIGHTELF)
    call SetPlayerRaceSelectable(Player(23), false)
    call SetPlayerController(Player(23), MAP_CONTROL_RESCUABLE)
    call SetPlayerAlliance(Player(23), Player(0), ALLIANCE_RESCUABLE, true)
    call SetPlayerAlliance(Player(23), Player(1), ALLIANCE_RESCUABLE, true)
    call SetPlayerAlliance(Player(23), Player(2), ALLIANCE_RESCUABLE, true)

endfunction

function InitCustomTeams takes nothing returns nothing
    // Force: TRIGSTR_017
    call SetPlayerTeam(Player(0), 0)
    call SetPlayerState(Player(0), PLAYER_STATE_ALLIED_VICTORY, 1)
    call SetPlayerTeam(Player(1), 0)
    call SetPlayerState(Player(1), PLAYER_STATE_ALLIED_VICTORY, 1)
    call SetPlayerTeam(Player(2), 0)
    call SetPlayerState(Player(2), PLAYER_STATE_ALLIED_VICTORY, 1)
    call SetPlayerTeam(Player(6), 0)
    call SetPlayerState(Player(6), PLAYER_STATE_ALLIED_VICTORY, 1)
    call SetPlayerTeam(Player(7), 0)
    call SetPlayerState(Player(7), PLAYER_STATE_ALLIED_VICTORY, 1)
    call SetPlayerTeam(Player(8), 0)
    call SetPlayerState(Player(8), PLAYER_STATE_ALLIED_VICTORY, 1)

    //   Allied
    call SetPlayerAllianceStateAllyBJ(Player(0), Player(1), true)
    call SetPlayerAllianceStateAllyBJ(Player(0), Player(2), true)
    call SetPlayerAllianceStateAllyBJ(Player(0), Player(6), true)
    call SetPlayerAllianceStateAllyBJ(Player(0), Player(7), true)
    call SetPlayerAllianceStateAllyBJ(Player(0), Player(8), true)
    call SetPlayerAllianceStateAllyBJ(Player(1), Player(0), true)
    call SetPlayerAllianceStateAllyBJ(Player(1), Player(2), true)
    call SetPlayerAllianceStateAllyBJ(Player(1), Player(6), true)
    call SetPlayerAllianceStateAllyBJ(Player(1), Player(7), true)
    call SetPlayerAllianceStateAllyBJ(Player(1), Player(8), true)
    call SetPlayerAllianceStateAllyBJ(Player(2), Player(0), true)
    call SetPlayerAllianceStateAllyBJ(Player(2), Player(1), true)
    call SetPlayerAllianceStateAllyBJ(Player(2), Player(6), true)
    call SetPlayerAllianceStateAllyBJ(Player(2), Player(7), true)
    call SetPlayerAllianceStateAllyBJ(Player(2), Player(8), true)
    call SetPlayerAllianceStateAllyBJ(Player(6), Player(0), true)
    call SetPlayerAllianceStateAllyBJ(Player(6), Player(1), true)
    call SetPlayerAllianceStateAllyBJ(Player(6), Player(2), true)
    call SetPlayerAllianceStateAllyBJ(Player(6), Player(7), true)
    call SetPlayerAllianceStateAllyBJ(Player(6), Player(8), true)
    call SetPlayerAllianceStateAllyBJ(Player(7), Player(0), true)
    call SetPlayerAllianceStateAllyBJ(Player(7), Player(1), true)
    call SetPlayerAllianceStateAllyBJ(Player(7), Player(2), true)
    call SetPlayerAllianceStateAllyBJ(Player(7), Player(6), true)
    call SetPlayerAllianceStateAllyBJ(Player(7), Player(8), true)
    call SetPlayerAllianceStateAllyBJ(Player(8), Player(0), true)
    call SetPlayerAllianceStateAllyBJ(Player(8), Player(1), true)
    call SetPlayerAllianceStateAllyBJ(Player(8), Player(2), true)
    call SetPlayerAllianceStateAllyBJ(Player(8), Player(6), true)
    call SetPlayerAllianceStateAllyBJ(Player(8), Player(7), true)

    //   Shared Vision
    call SetPlayerAllianceStateVisionBJ(Player(0), Player(1), true)
    call SetPlayerAllianceStateVisionBJ(Player(0), Player(2), true)
    call SetPlayerAllianceStateVisionBJ(Player(0), Player(6), true)
    call SetPlayerAllianceStateVisionBJ(Player(0), Player(7), true)
    call SetPlayerAllianceStateVisionBJ(Player(0), Player(8), true)
    call SetPlayerAllianceStateVisionBJ(Player(1), Player(0), true)
    call SetPlayerAllianceStateVisionBJ(Player(1), Player(2), true)
    call SetPlayerAllianceStateVisionBJ(Player(1), Player(6), true)
    call SetPlayerAllianceStateVisionBJ(Player(1), Player(7), true)
    call SetPlayerAllianceStateVisionBJ(Player(1), Player(8), true)
    call SetPlayerAllianceStateVisionBJ(Player(2), Player(0), true)
    call SetPlayerAllianceStateVisionBJ(Player(2), Player(1), true)
    call SetPlayerAllianceStateVisionBJ(Player(2), Player(6), true)
    call SetPlayerAllianceStateVisionBJ(Player(2), Player(7), true)
    call SetPlayerAllianceStateVisionBJ(Player(2), Player(8), true)
    call SetPlayerAllianceStateVisionBJ(Player(6), Player(0), true)
    call SetPlayerAllianceStateVisionBJ(Player(6), Player(1), true)
    call SetPlayerAllianceStateVisionBJ(Player(6), Player(2), true)
    call SetPlayerAllianceStateVisionBJ(Player(6), Player(7), true)
    call SetPlayerAllianceStateVisionBJ(Player(6), Player(8), true)
    call SetPlayerAllianceStateVisionBJ(Player(7), Player(0), true)
    call SetPlayerAllianceStateVisionBJ(Player(7), Player(1), true)
    call SetPlayerAllianceStateVisionBJ(Player(7), Player(2), true)
    call SetPlayerAllianceStateVisionBJ(Player(7), Player(6), true)
    call SetPlayerAllianceStateVisionBJ(Player(7), Player(8), true)
    call SetPlayerAllianceStateVisionBJ(Player(8), Player(0), true)
    call SetPlayerAllianceStateVisionBJ(Player(8), Player(1), true)
    call SetPlayerAllianceStateVisionBJ(Player(8), Player(2), true)
    call SetPlayerAllianceStateVisionBJ(Player(8), Player(6), true)
    call SetPlayerAllianceStateVisionBJ(Player(8), Player(7), true)

    //   Shared Control
    call SetPlayerAllianceStateControlBJ(Player(0), Player(1), true)
    call SetPlayerAllianceStateControlBJ(Player(0), Player(2), true)
    call SetPlayerAllianceStateControlBJ(Player(0), Player(6), true)
    call SetPlayerAllianceStateControlBJ(Player(0), Player(7), true)
    call SetPlayerAllianceStateControlBJ(Player(0), Player(8), true)
    call SetPlayerAllianceStateControlBJ(Player(1), Player(0), true)
    call SetPlayerAllianceStateControlBJ(Player(1), Player(2), true)
    call SetPlayerAllianceStateControlBJ(Player(1), Player(6), true)
    call SetPlayerAllianceStateControlBJ(Player(1), Player(7), true)
    call SetPlayerAllianceStateControlBJ(Player(1), Player(8), true)
    call SetPlayerAllianceStateControlBJ(Player(2), Player(0), true)
    call SetPlayerAllianceStateControlBJ(Player(2), Player(1), true)
    call SetPlayerAllianceStateControlBJ(Player(2), Player(6), true)
    call SetPlayerAllianceStateControlBJ(Player(2), Player(7), true)
    call SetPlayerAllianceStateControlBJ(Player(2), Player(8), true)
    call SetPlayerAllianceStateControlBJ(Player(6), Player(0), true)
    call SetPlayerAllianceStateControlBJ(Player(6), Player(1), true)
    call SetPlayerAllianceStateControlBJ(Player(6), Player(2), true)
    call SetPlayerAllianceStateControlBJ(Player(6), Player(7), true)
    call SetPlayerAllianceStateControlBJ(Player(6), Player(8), true)
    call SetPlayerAllianceStateControlBJ(Player(7), Player(0), true)
    call SetPlayerAllianceStateControlBJ(Player(7), Player(1), true)
    call SetPlayerAllianceStateControlBJ(Player(7), Player(2), true)
    call SetPlayerAllianceStateControlBJ(Player(7), Player(6), true)
    call SetPlayerAllianceStateControlBJ(Player(7), Player(8), true)
    call SetPlayerAllianceStateControlBJ(Player(8), Player(0), true)
    call SetPlayerAllianceStateControlBJ(Player(8), Player(1), true)
    call SetPlayerAllianceStateControlBJ(Player(8), Player(2), true)
    call SetPlayerAllianceStateControlBJ(Player(8), Player(6), true)
    call SetPlayerAllianceStateControlBJ(Player(8), Player(7), true)

    //   Shared Advanced Control
    call SetPlayerAllianceStateFullControlBJ(Player(0), Player(1), true)
    call SetPlayerAllianceStateFullControlBJ(Player(0), Player(2), true)
    call SetPlayerAllianceStateFullControlBJ(Player(0), Player(6), true)
    call SetPlayerAllianceStateFullControlBJ(Player(0), Player(7), true)
    call SetPlayerAllianceStateFullControlBJ(Player(0), Player(8), true)
    call SetPlayerAllianceStateFullControlBJ(Player(1), Player(0), true)
    call SetPlayerAllianceStateFullControlBJ(Player(1), Player(2), true)
    call SetPlayerAllianceStateFullControlBJ(Player(1), Player(6), true)
    call SetPlayerAllianceStateFullControlBJ(Player(1), Player(7), true)
    call SetPlayerAllianceStateFullControlBJ(Player(1), Player(8), true)
    call SetPlayerAllianceStateFullControlBJ(Player(2), Player(0), true)
    call SetPlayerAllianceStateFullControlBJ(Player(2), Player(1), true)
    call SetPlayerAllianceStateFullControlBJ(Player(2), Player(6), true)
    call SetPlayerAllianceStateFullControlBJ(Player(2), Player(7), true)
    call SetPlayerAllianceStateFullControlBJ(Player(2), Player(8), true)
    call SetPlayerAllianceStateFullControlBJ(Player(6), Player(0), true)
    call SetPlayerAllianceStateFullControlBJ(Player(6), Player(1), true)
    call SetPlayerAllianceStateFullControlBJ(Player(6), Player(2), true)
    call SetPlayerAllianceStateFullControlBJ(Player(6), Player(7), true)
    call SetPlayerAllianceStateFullControlBJ(Player(6), Player(8), true)
    call SetPlayerAllianceStateFullControlBJ(Player(7), Player(0), true)
    call SetPlayerAllianceStateFullControlBJ(Player(7), Player(1), true)
    call SetPlayerAllianceStateFullControlBJ(Player(7), Player(2), true)
    call SetPlayerAllianceStateFullControlBJ(Player(7), Player(6), true)
    call SetPlayerAllianceStateFullControlBJ(Player(7), Player(8), true)
    call SetPlayerAllianceStateFullControlBJ(Player(8), Player(0), true)
    call SetPlayerAllianceStateFullControlBJ(Player(8), Player(1), true)
    call SetPlayerAllianceStateFullControlBJ(Player(8), Player(2), true)
    call SetPlayerAllianceStateFullControlBJ(Player(8), Player(6), true)
    call SetPlayerAllianceStateFullControlBJ(Player(8), Player(7), true)

    // Force: TRIGSTR_018
    call SetPlayerTeam(Player(12), 1)
    call SetPlayerTeam(Player(14), 1)
    call SetPlayerTeam(Player(23), 1)

    //   Allied
    call SetPlayerAllianceStateAllyBJ(Player(12), Player(14), true)
    call SetPlayerAllianceStateAllyBJ(Player(12), Player(23), true)
    call SetPlayerAllianceStateAllyBJ(Player(14), Player(12), true)
    call SetPlayerAllianceStateAllyBJ(Player(14), Player(23), true)
    call SetPlayerAllianceStateAllyBJ(Player(23), Player(12), true)
    call SetPlayerAllianceStateAllyBJ(Player(23), Player(14), true)

    //   Shared Vision
    call SetPlayerAllianceStateVisionBJ(Player(12), Player(14), true)
    call SetPlayerAllianceStateVisionBJ(Player(12), Player(23), true)
    call SetPlayerAllianceStateVisionBJ(Player(14), Player(12), true)
    call SetPlayerAllianceStateVisionBJ(Player(14), Player(23), true)
    call SetPlayerAllianceStateVisionBJ(Player(23), Player(12), true)
    call SetPlayerAllianceStateVisionBJ(Player(23), Player(14), true)

    // Force: TRIGSTR_019
    call SetPlayerTeam(Player(13), 2)
    call SetPlayerTeam(Player(21), 2)
    call SetPlayerTeam(Player(22), 2)

endfunction

function InitAllyPriorities takes nothing returns nothing

    call SetStartLocPrioCount(0, 1)
    call SetStartLocPrio(0, 0, 2, MAP_LOC_PRIO_HIGH)

    call SetStartLocPrioCount(1, 2)
    call SetStartLocPrio(1, 0, 0, MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(1, 1, 2, MAP_LOC_PRIO_LOW)

    call SetStartLocPrioCount(2, 1)
    call SetStartLocPrio(2, 0, 0, MAP_LOC_PRIO_HIGH)

    call SetStartLocPrioCount(3, 3)
    call SetStartLocPrio(3, 0, 0, MAP_LOC_PRIO_LOW)
    call SetStartLocPrio(3, 1, 1, MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(3, 2, 2, MAP_LOC_PRIO_LOW)
endfunction

//***************************************************************************
//*
//*  Main Initialization
//*
//***************************************************************************

//===========================================================================
function main takes nothing returns nothing
    call SetCameraBounds(- 3328.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), - 1536.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM), 3328.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), 1024.0 - GetCameraMargin(CAMERA_MARGIN_TOP), - 3328.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), 1024.0 - GetCameraMargin(CAMERA_MARGIN_TOP), 3328.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), - 1536.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM))
    call SetDayNightModels("Environment\\DNC\\DNCLordaeron\\DNCLordaeronTerrain\\DNCLordaeronTerrain.mdl", "Environment\\DNC\\DNCLordaeron\\DNCLordaeronUnit\\DNCLordaeronUnit.mdl")
    call NewSoundEnvironment("Default")
    call SetAmbientDaySound("CityScapeDay")
    call SetAmbientNightSound("CityScapeNight")
    call SetMapMusic("Music", true, 0)
    call CreateAllUnits()
    call InitBlizzard()


    call InitGlobals()
    call InitTrig_Melee_Initialization() // INLINED!!
    call ConditionalTriggerExecute(gg_trg_Melee_Initialization) // INLINED!!

endfunction

//***************************************************************************
//*
//*  Map Configuration
//*
//***************************************************************************

function config takes nothing returns nothing
    call SetMapName("TRIGSTR_001")
    call SetMapDescription("TRIGSTR_003")
    call SetPlayers(12)
    call SetTeams(12)
    call SetGamePlacement(MAP_PLACEMENT_TEAMS_TOGETHER)

    call DefineStartLocation(0, 512.0, 0.0)
    call DefineStartLocation(1, 0.0, - 512.0)
    call DefineStartLocation(2, 384.0, 384.0)
    call DefineStartLocation(3, - 512.0, 0.0)
    call DefineStartLocation(4, - 384.0, - 384.0)
    call DefineStartLocation(5, 384.0, - 384.0)
    call DefineStartLocation(6, - 128.0, - 128.0)
    call DefineStartLocation(7, - 384.0, 384.0)
    call DefineStartLocation(8, 128.0, 128.0)
    call DefineStartLocation(9, 128.0, - 128.0)
    call DefineStartLocation(10, 0.0, 512.0)
    call DefineStartLocation(11, - 128.0, 128.0)

    // Player setup
    call InitCustomPlayerSlots()
    call InitCustomTeams()
    call InitAllyPriorities()
endfunction




//Struct method generated initializers/callers:

