gg_trg_Melee_Initialization = nil
function InitGlobals()
end

function CreateUnitsForPlayer0()
    local p = Player(0)
    local u
    local unitID
    local t
    local life
    u = CreateUnit(p, FourCC("Hblm"), 2.6, -6.2, 45.000)
end

function CreatePlayerBuildings()
end

function CreatePlayerUnits()
    CreateUnitsForPlayer0()
end

function CreateAllUnits()
    CreatePlayerBuildings()
    CreatePlayerUnits()
end

function Trig_Melee_Initialization_Actions()
    MeleeStartingVisibility()
    MeleeStartingHeroLimit()
    MeleeGrantHeroItems()
    MeleeStartingResources()
    MeleeClearExcessUnits()
    MeleeStartingUnits()
    MeleeStartingAI()
    MeleeInitVictoryDefeat()
end

function InitTrig_Melee_Initialization()
    gg_trg_Melee_Initialization = CreateTrigger()
    TriggerAddAction(gg_trg_Melee_Initialization, Trig_Melee_Initialization_Actions)
end

function InitCustomTriggers()
    InitTrig_Melee_Initialization()
end

function RunInitializationTriggers()
    ConditionalTriggerExecute(gg_trg_Melee_Initialization)
end

function InitCustomPlayerSlots()
    SetPlayerStartLocation(Player(0), 0)
    SetPlayerColor(Player(0), ConvertPlayerColor(0))
    SetPlayerRacePreference(Player(0), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(0), false)
    SetPlayerController(Player(0), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(1), 1)
    SetPlayerColor(Player(1), ConvertPlayerColor(1))
    SetPlayerRacePreference(Player(1), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(1), false)
    SetPlayerController(Player(1), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(2), 2)
    SetPlayerColor(Player(2), ConvertPlayerColor(2))
    SetPlayerRacePreference(Player(2), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(2), false)
    SetPlayerController(Player(2), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(6), 3)
    SetPlayerColor(Player(6), ConvertPlayerColor(6))
    SetPlayerRacePreference(Player(6), RACE_PREF_ORC)
    SetPlayerRaceSelectable(Player(6), false)
    SetPlayerController(Player(6), MAP_CONTROL_COMPUTER)
    SetPlayerStartLocation(Player(7), 4)
    SetPlayerColor(Player(7), ConvertPlayerColor(7))
    SetPlayerRacePreference(Player(7), RACE_PREF_ORC)
    SetPlayerRaceSelectable(Player(7), false)
    SetPlayerController(Player(7), MAP_CONTROL_COMPUTER)
    SetPlayerStartLocation(Player(8), 5)
    SetPlayerColor(Player(8), ConvertPlayerColor(8))
    SetPlayerRacePreference(Player(8), RACE_PREF_ORC)
    SetPlayerRaceSelectable(Player(8), false)
    SetPlayerController(Player(8), MAP_CONTROL_COMPUTER)
    SetPlayerStartLocation(Player(12), 6)
    ForcePlayerStartLocation(Player(12), 6)
    SetPlayerColor(Player(12), ConvertPlayerColor(12))
    SetPlayerRacePreference(Player(12), RACE_PREF_UNDEAD)
    SetPlayerRaceSelectable(Player(12), false)
    SetPlayerController(Player(12), MAP_CONTROL_NEUTRAL)
    SetPlayerStartLocation(Player(13), 7)
    ForcePlayerStartLocation(Player(13), 7)
    SetPlayerColor(Player(13), ConvertPlayerColor(13))
    SetPlayerRacePreference(Player(13), RACE_PREF_UNDEAD)
    SetPlayerRaceSelectable(Player(13), false)
    SetPlayerController(Player(13), MAP_CONTROL_NEUTRAL)
    SetPlayerStartLocation(Player(14), 8)
    ForcePlayerStartLocation(Player(14), 8)
    SetPlayerColor(Player(14), ConvertPlayerColor(14))
    SetPlayerRacePreference(Player(14), RACE_PREF_UNDEAD)
    SetPlayerRaceSelectable(Player(14), false)
    SetPlayerController(Player(14), MAP_CONTROL_NEUTRAL)
    SetPlayerStartLocation(Player(21), 9)
    ForcePlayerStartLocation(Player(21), 9)
    SetPlayerColor(Player(21), ConvertPlayerColor(21))
    SetPlayerRacePreference(Player(21), RACE_PREF_NIGHTELF)
    SetPlayerRaceSelectable(Player(21), false)
    SetPlayerController(Player(21), MAP_CONTROL_RESCUABLE)
    SetPlayerAlliance(Player(21), Player(0), ALLIANCE_RESCUABLE, true)
    SetPlayerAlliance(Player(21), Player(1), ALLIANCE_RESCUABLE, true)
    SetPlayerAlliance(Player(21), Player(2), ALLIANCE_RESCUABLE, true)
    SetPlayerStartLocation(Player(22), 10)
    ForcePlayerStartLocation(Player(22), 10)
    SetPlayerColor(Player(22), ConvertPlayerColor(22))
    SetPlayerRacePreference(Player(22), RACE_PREF_NIGHTELF)
    SetPlayerRaceSelectable(Player(22), false)
    SetPlayerController(Player(22), MAP_CONTROL_RESCUABLE)
    SetPlayerAlliance(Player(22), Player(0), ALLIANCE_RESCUABLE, true)
    SetPlayerAlliance(Player(22), Player(1), ALLIANCE_RESCUABLE, true)
    SetPlayerAlliance(Player(22), Player(2), ALLIANCE_RESCUABLE, true)
    SetPlayerStartLocation(Player(23), 11)
    ForcePlayerStartLocation(Player(23), 11)
    SetPlayerColor(Player(23), ConvertPlayerColor(23))
    SetPlayerRacePreference(Player(23), RACE_PREF_NIGHTELF)
    SetPlayerRaceSelectable(Player(23), false)
    SetPlayerController(Player(23), MAP_CONTROL_RESCUABLE)
    SetPlayerAlliance(Player(23), Player(0), ALLIANCE_RESCUABLE, true)
    SetPlayerAlliance(Player(23), Player(1), ALLIANCE_RESCUABLE, true)
    SetPlayerAlliance(Player(23), Player(2), ALLIANCE_RESCUABLE, true)
end

function InitCustomTeams()
    SetPlayerTeam(Player(0), 0)
    SetPlayerState(Player(0), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(1), 0)
    SetPlayerState(Player(1), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(2), 0)
    SetPlayerState(Player(2), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(6), 0)
    SetPlayerState(Player(6), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(7), 0)
    SetPlayerState(Player(7), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(8), 0)
    SetPlayerState(Player(8), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerAllianceStateAllyBJ(Player(0), Player(1), true)
    SetPlayerAllianceStateAllyBJ(Player(0), Player(2), true)
    SetPlayerAllianceStateAllyBJ(Player(0), Player(6), true)
    SetPlayerAllianceStateAllyBJ(Player(0), Player(7), true)
    SetPlayerAllianceStateAllyBJ(Player(0), Player(8), true)
    SetPlayerAllianceStateAllyBJ(Player(1), Player(0), true)
    SetPlayerAllianceStateAllyBJ(Player(1), Player(2), true)
    SetPlayerAllianceStateAllyBJ(Player(1), Player(6), true)
    SetPlayerAllianceStateAllyBJ(Player(1), Player(7), true)
    SetPlayerAllianceStateAllyBJ(Player(1), Player(8), true)
    SetPlayerAllianceStateAllyBJ(Player(2), Player(0), true)
    SetPlayerAllianceStateAllyBJ(Player(2), Player(1), true)
    SetPlayerAllianceStateAllyBJ(Player(2), Player(6), true)
    SetPlayerAllianceStateAllyBJ(Player(2), Player(7), true)
    SetPlayerAllianceStateAllyBJ(Player(2), Player(8), true)
    SetPlayerAllianceStateAllyBJ(Player(6), Player(0), true)
    SetPlayerAllianceStateAllyBJ(Player(6), Player(1), true)
    SetPlayerAllianceStateAllyBJ(Player(6), Player(2), true)
    SetPlayerAllianceStateAllyBJ(Player(6), Player(7), true)
    SetPlayerAllianceStateAllyBJ(Player(6), Player(8), true)
    SetPlayerAllianceStateAllyBJ(Player(7), Player(0), true)
    SetPlayerAllianceStateAllyBJ(Player(7), Player(1), true)
    SetPlayerAllianceStateAllyBJ(Player(7), Player(2), true)
    SetPlayerAllianceStateAllyBJ(Player(7), Player(6), true)
    SetPlayerAllianceStateAllyBJ(Player(7), Player(8), true)
    SetPlayerAllianceStateAllyBJ(Player(8), Player(0), true)
    SetPlayerAllianceStateAllyBJ(Player(8), Player(1), true)
    SetPlayerAllianceStateAllyBJ(Player(8), Player(2), true)
    SetPlayerAllianceStateAllyBJ(Player(8), Player(6), true)
    SetPlayerAllianceStateAllyBJ(Player(8), Player(7), true)
    SetPlayerAllianceStateVisionBJ(Player(0), Player(1), true)
    SetPlayerAllianceStateVisionBJ(Player(0), Player(2), true)
    SetPlayerAllianceStateVisionBJ(Player(0), Player(6), true)
    SetPlayerAllianceStateVisionBJ(Player(0), Player(7), true)
    SetPlayerAllianceStateVisionBJ(Player(0), Player(8), true)
    SetPlayerAllianceStateVisionBJ(Player(1), Player(0), true)
    SetPlayerAllianceStateVisionBJ(Player(1), Player(2), true)
    SetPlayerAllianceStateVisionBJ(Player(1), Player(6), true)
    SetPlayerAllianceStateVisionBJ(Player(1), Player(7), true)
    SetPlayerAllianceStateVisionBJ(Player(1), Player(8), true)
    SetPlayerAllianceStateVisionBJ(Player(2), Player(0), true)
    SetPlayerAllianceStateVisionBJ(Player(2), Player(1), true)
    SetPlayerAllianceStateVisionBJ(Player(2), Player(6), true)
    SetPlayerAllianceStateVisionBJ(Player(2), Player(7), true)
    SetPlayerAllianceStateVisionBJ(Player(2), Player(8), true)
    SetPlayerAllianceStateVisionBJ(Player(6), Player(0), true)
    SetPlayerAllianceStateVisionBJ(Player(6), Player(1), true)
    SetPlayerAllianceStateVisionBJ(Player(6), Player(2), true)
    SetPlayerAllianceStateVisionBJ(Player(6), Player(7), true)
    SetPlayerAllianceStateVisionBJ(Player(6), Player(8), true)
    SetPlayerAllianceStateVisionBJ(Player(7), Player(0), true)
    SetPlayerAllianceStateVisionBJ(Player(7), Player(1), true)
    SetPlayerAllianceStateVisionBJ(Player(7), Player(2), true)
    SetPlayerAllianceStateVisionBJ(Player(7), Player(6), true)
    SetPlayerAllianceStateVisionBJ(Player(7), Player(8), true)
    SetPlayerAllianceStateVisionBJ(Player(8), Player(0), true)
    SetPlayerAllianceStateVisionBJ(Player(8), Player(1), true)
    SetPlayerAllianceStateVisionBJ(Player(8), Player(2), true)
    SetPlayerAllianceStateVisionBJ(Player(8), Player(6), true)
    SetPlayerAllianceStateVisionBJ(Player(8), Player(7), true)
    SetPlayerAllianceStateControlBJ(Player(0), Player(1), true)
    SetPlayerAllianceStateControlBJ(Player(0), Player(2), true)
    SetPlayerAllianceStateControlBJ(Player(0), Player(6), true)
    SetPlayerAllianceStateControlBJ(Player(0), Player(7), true)
    SetPlayerAllianceStateControlBJ(Player(0), Player(8), true)
    SetPlayerAllianceStateControlBJ(Player(1), Player(0), true)
    SetPlayerAllianceStateControlBJ(Player(1), Player(2), true)
    SetPlayerAllianceStateControlBJ(Player(1), Player(6), true)
    SetPlayerAllianceStateControlBJ(Player(1), Player(7), true)
    SetPlayerAllianceStateControlBJ(Player(1), Player(8), true)
    SetPlayerAllianceStateControlBJ(Player(2), Player(0), true)
    SetPlayerAllianceStateControlBJ(Player(2), Player(1), true)
    SetPlayerAllianceStateControlBJ(Player(2), Player(6), true)
    SetPlayerAllianceStateControlBJ(Player(2), Player(7), true)
    SetPlayerAllianceStateControlBJ(Player(2), Player(8), true)
    SetPlayerAllianceStateControlBJ(Player(6), Player(0), true)
    SetPlayerAllianceStateControlBJ(Player(6), Player(1), true)
    SetPlayerAllianceStateControlBJ(Player(6), Player(2), true)
    SetPlayerAllianceStateControlBJ(Player(6), Player(7), true)
    SetPlayerAllianceStateControlBJ(Player(6), Player(8), true)
    SetPlayerAllianceStateControlBJ(Player(7), Player(0), true)
    SetPlayerAllianceStateControlBJ(Player(7), Player(1), true)
    SetPlayerAllianceStateControlBJ(Player(7), Player(2), true)
    SetPlayerAllianceStateControlBJ(Player(7), Player(6), true)
    SetPlayerAllianceStateControlBJ(Player(7), Player(8), true)
    SetPlayerAllianceStateControlBJ(Player(8), Player(0), true)
    SetPlayerAllianceStateControlBJ(Player(8), Player(1), true)
    SetPlayerAllianceStateControlBJ(Player(8), Player(2), true)
    SetPlayerAllianceStateControlBJ(Player(8), Player(6), true)
    SetPlayerAllianceStateControlBJ(Player(8), Player(7), true)
    SetPlayerAllianceStateFullControlBJ(Player(0), Player(1), true)
    SetPlayerAllianceStateFullControlBJ(Player(0), Player(2), true)
    SetPlayerAllianceStateFullControlBJ(Player(0), Player(6), true)
    SetPlayerAllianceStateFullControlBJ(Player(0), Player(7), true)
    SetPlayerAllianceStateFullControlBJ(Player(0), Player(8), true)
    SetPlayerAllianceStateFullControlBJ(Player(1), Player(0), true)
    SetPlayerAllianceStateFullControlBJ(Player(1), Player(2), true)
    SetPlayerAllianceStateFullControlBJ(Player(1), Player(6), true)
    SetPlayerAllianceStateFullControlBJ(Player(1), Player(7), true)
    SetPlayerAllianceStateFullControlBJ(Player(1), Player(8), true)
    SetPlayerAllianceStateFullControlBJ(Player(2), Player(0), true)
    SetPlayerAllianceStateFullControlBJ(Player(2), Player(1), true)
    SetPlayerAllianceStateFullControlBJ(Player(2), Player(6), true)
    SetPlayerAllianceStateFullControlBJ(Player(2), Player(7), true)
    SetPlayerAllianceStateFullControlBJ(Player(2), Player(8), true)
    SetPlayerAllianceStateFullControlBJ(Player(6), Player(0), true)
    SetPlayerAllianceStateFullControlBJ(Player(6), Player(1), true)
    SetPlayerAllianceStateFullControlBJ(Player(6), Player(2), true)
    SetPlayerAllianceStateFullControlBJ(Player(6), Player(7), true)
    SetPlayerAllianceStateFullControlBJ(Player(6), Player(8), true)
    SetPlayerAllianceStateFullControlBJ(Player(7), Player(0), true)
    SetPlayerAllianceStateFullControlBJ(Player(7), Player(1), true)
    SetPlayerAllianceStateFullControlBJ(Player(7), Player(2), true)
    SetPlayerAllianceStateFullControlBJ(Player(7), Player(6), true)
    SetPlayerAllianceStateFullControlBJ(Player(7), Player(8), true)
    SetPlayerAllianceStateFullControlBJ(Player(8), Player(0), true)
    SetPlayerAllianceStateFullControlBJ(Player(8), Player(1), true)
    SetPlayerAllianceStateFullControlBJ(Player(8), Player(2), true)
    SetPlayerAllianceStateFullControlBJ(Player(8), Player(6), true)
    SetPlayerAllianceStateFullControlBJ(Player(8), Player(7), true)
    SetPlayerTeam(Player(12), 1)
    SetPlayerTeam(Player(14), 1)
    SetPlayerTeam(Player(23), 1)
    SetPlayerAllianceStateAllyBJ(Player(12), Player(14), true)
    SetPlayerAllianceStateAllyBJ(Player(12), Player(23), true)
    SetPlayerAllianceStateAllyBJ(Player(14), Player(12), true)
    SetPlayerAllianceStateAllyBJ(Player(14), Player(23), true)
    SetPlayerAllianceStateAllyBJ(Player(23), Player(12), true)
    SetPlayerAllianceStateAllyBJ(Player(23), Player(14), true)
    SetPlayerAllianceStateVisionBJ(Player(12), Player(14), true)
    SetPlayerAllianceStateVisionBJ(Player(12), Player(23), true)
    SetPlayerAllianceStateVisionBJ(Player(14), Player(12), true)
    SetPlayerAllianceStateVisionBJ(Player(14), Player(23), true)
    SetPlayerAllianceStateVisionBJ(Player(23), Player(12), true)
    SetPlayerAllianceStateVisionBJ(Player(23), Player(14), true)
    SetPlayerTeam(Player(13), 2)
    SetPlayerTeam(Player(21), 2)
    SetPlayerTeam(Player(22), 2)
end

function InitAllyPriorities()
    SetStartLocPrioCount(0, 1)
    SetStartLocPrio(0, 0, 2, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(1, 2)
    SetStartLocPrio(1, 0, 0, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(1, 1, 2, MAP_LOC_PRIO_LOW)
    SetStartLocPrioCount(2, 1)
    SetStartLocPrio(2, 0, 0, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(3, 3)
    SetStartLocPrio(3, 0, 0, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(3, 1, 1, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(3, 2, 2, MAP_LOC_PRIO_LOW)
end

function main()
    SetCameraBounds(-3328.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), -1536.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM), 3328.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), 1024.0 - GetCameraMargin(CAMERA_MARGIN_TOP), -3328.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), 1024.0 - GetCameraMargin(CAMERA_MARGIN_TOP), 3328.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), -1536.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM))
    SetDayNightModels("Environment\\DNC\\DNCLordaeron\\DNCLordaeronTerrain\\DNCLordaeronTerrain.mdl", "Environment\\DNC\\DNCLordaeron\\DNCLordaeronUnit\\DNCLordaeronUnit.mdl")
    NewSoundEnvironment("Default")
    SetAmbientDaySound("CityScapeDay")
    SetAmbientNightSound("CityScapeNight")
    SetMapMusic("Music", true, 0)
    CreateAllUnits()
    InitBlizzard()
    InitGlobals()
    InitCustomTriggers()
    RunInitializationTriggers()
end

function config()
    SetMapName("TRIGSTR_001")
    SetMapDescription("TRIGSTR_003")
    SetPlayers(12)
    SetTeams(12)
    SetGamePlacement(MAP_PLACEMENT_TEAMS_TOGETHER)
    DefineStartLocation(0, 512.0, 0.0)
    DefineStartLocation(1, 0.0, -512.0)
    DefineStartLocation(2, 384.0, 384.0)
    DefineStartLocation(3, -512.0, 0.0)
    DefineStartLocation(4, -384.0, -384.0)
    DefineStartLocation(5, 384.0, -384.0)
    DefineStartLocation(6, -128.0, -128.0)
    DefineStartLocation(7, -384.0, 384.0)
    DefineStartLocation(8, 128.0, 128.0)
    DefineStartLocation(9, 128.0, -128.0)
    DefineStartLocation(10, 0.0, 512.0)
    DefineStartLocation(11, -128.0, 128.0)
    InitCustomPlayerSlots()
    InitCustomTeams()
    InitAllyPriorities()
end

